# Generated by Django 4.2.17 on 2025-05-27 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0002_approveduser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApprovedUser",
        ),
        migrations.RenameField(
            model_name="accessrequest",
            old_name="requested_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="accessrequest",
            old_name="approved",
            new_name="is_approved",
        ),
        migrations.RemoveField(
            model_name="accessrequest",
            name="email",
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
