# Generated by Django 4.2.17 on 2025-05-27 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0003_delete_approveduser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
